.TH SUPERB-HR "1" "2021" "NNB" "User Commands"
.SH NAME
SuperB HR \- Portable horizontal ruler for terminal
.SH SYNOPSIS
.B hr [TEXTS]
.SH DESCRIPTION
SuperB HR is a CLI tool to render horizontal ruler/line in the terminal.
.SH ENVIRONMENT VARIABLES
\fBHR_DEFAULT_TEXT\fR
change SuperB HR's default text (default: ─)
.SH REPORTING BUGS
Report bugs to https://github.com/NNBnh/hr/issues
